name: dukalink
description: A lightweight ecommerce experience with delivery tracking and Scan QR code features.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

# Observe that the dependencies are arranged alphabetically for easier visiblity and updating.
dependencies:
  flutter:
    sdk: flutter
  
  async_redux: ^19.0.2
  cloud_firestore: ^4.5.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_analytics: ^10.2.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_crashlytics: ^3.1.0
  flutter_native_splash: ^2.2.19
  freezed: ^2.3.2
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  logger: ^1.3.0
  pin_code_fields: ^7.4.0
  progress_state_button: ^1.0.4
  rxdart: ^0.27.7
  sqflite: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  built_value_generator: ^8.4.4
  freezed_annotation: ^2.2.0
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0
  lint: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/logo.png

  # To add custom fonts to your application, add a fonts section here.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic


# This package generates native code to customize Flutter's default white native splash screen
flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#42a5f5"
  background_image: "assets/logo/logo.png"

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:


